version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/pkg/db/mydb.db:/app/pkg/db/mydb.db
    environment:
      - DB_PATH=/app/pkg/db/mydb.db

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
