version: '3.8'

services:
  backend:
    image: golang:1.22.3
    working_dir: /app
    volumes:
      - ./backend:/app 
    command: bash -c "go build -o main . && ./main"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - GO_ENV=development
   


  frontend:
    image: node:18  
    working_dir: /app
    volumes:
      - ./frontend:/app  
    command: bash -c "npm install && npm run dockerize"
    ports:
      - "4200:4200"
    expose:
      - "4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend 